# Generated by Selenium IDE
# 1 - Bibliotecas / Imports
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

# 2 - Classe (Grupo de Definições / Métodos ou Funções)
class TestIncluirUsuario():

    # 3 - Definições / Métodos ou Funções
    # 3.1 - Configura ou Prepara

    # 3.1.1 - método de inicialização / para ligar o Selenium WebDriver
    def setup_method(self, method):

        self.driver = \
         webdriver.Chrome('C:\\Users\\corre\\PycharmProjects\\133pets\\vendors\\drivers\\chrome\\100\\chromedriver.exe')
         # instanciando o Selenium/carregando na memoria
        self.vars = {}  # criando uma lista vazia

    # 3.1.2 - método de encerramento / para desligar o Selenium WebDriver
    def teardown_method(self, method):
        self.driver.quit() # destroi o objeto do Selenium/descarrega da memória

    # 3.2 - Executa e 3.3 - Valida (Podem ficar intercalados)
    # 3.2.1 - Método de Teste
    def test_incluirUsuario(self):
        self.driver.get("https://blazedemo.com/")               # abrir a URL
        self.driver.set_window_size(1296, 744)                  # ajusta o tamanho da janela
        self.driver.find_element(By.LINK_TEXT, "home").click()  # clica no link Home
        self.driver.find_element(By.LINK_TEXT, "Register").click()
        self.driver.find_element(By.ID, "name").send_keys("Jose Correia")
        self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(2)").click()
        self.driver.find_element(By.ID, "company").click()
        self.driver.find_element(By.ID, "company").send_keys("Iterasys")
        self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(3)").click()
        self.driver.find_element(By.ID, "email").click()
        self.driver.find_element(By.ID, "email").send_keys("correia@iterasys.com.br")
        self.driver.find_element(By.ID, "password").click()
        self.driver.find_element(By.ID, "password").send_keys("teste123")
        self.driver.find_element(By.ID, "password-confirm").click()
        self.driver.find_element(By.ID, "password-confirm").send_keys("teste123")
        self.driver.find_element(By.CSS_SELECTOR, ".btn").click()

        # 3.3.1 - Validar se exibe a mensagem de e-mail já cadastrado
        assert self.driver.find_element(By.CSS_SELECTOR, "strong").text == "The email has already been taken."

